const ActionConstants = {
  TEST: 'TEST',
  GET_ERROR: 'GET_ERROR',
  REGISTER_USER: 'REGISTER_USER',
  LOGIN_USER: 'LOGIN_USER',
  LOGOUT_USER: 'LOGOUT_USER',
  GET_PROFILE: 'GET_PROFILE',
  GET_PROFILES: 'GET_PROFILES',
  LOADING_PROFILE: 'LOADING_PROFILE',
  NOT_FOUND_PROFILE: 'NOT_FOUND_PROFILE',
  CLEAR_CURRENT_PROFILE: 'CLEAR_CURRENT_PROFILE',
};

export default ActionConstants;
