const ActionConstants = {
  // Error
  SET_ERROR: 'SET_ERROR',
  // User
  LOGIN_USER: 'LOGIN_USER',
  LOGOUT_USER: 'LOGOUT_USER',
  // Profile
  SET_PROFILE: 'SET_PROFILE',
  SET_PROFILES: 'SET_PROFILES',
  SET_LOADING_PROFILE: 'SET_LOADING_PROFILE',
  // Post
  SET_POST: 'SET_POST',
  SET_POSTS: 'SET_POSTS',
  SET_LOADING_POST: 'SET_LOADING_POST',
  REMOVE_POST: 'REMOVE_POST',
};

export default ActionConstants;
